### PR TITLE
Add initial support for netstandard.

### PR DESCRIPTION
**Pull request by byme8**
This PR adds support for netstandard as a generation target.

The final goal is to use ZeroQL for .Net Framework, Xamarin, and Unity.

Fixes: #46

### CODE REVIEW

**Review by JuanuMusic — APPROVED** [review]

**Comment by JuanuMusic** [comment]
This looks promising!

**Comment by JuanuMusic** [comment]
Let me know if I can help with anything.
I'll start by running this branch with my project and then try to go to Unity

**Comment by byme8** [comment]
I managed to test it for the .Net Framework console app, Xamarin Forms app, and Unity.

In the Unity case, you have to create a separate netstandard library and then copy assemblies to Unity assets. I see that there is a [way ](https://docs.unity3d.com/Manual/roslyn-analyzers.html) to enable source generators for unity. However, I did not try it.

**Comment by JuanuMusic** [comment]
> I managed to test it for the .Net Framework console app, Xamarin Forms app, and Unity.
> 
> In the Unity case, you have to create a separate netstandard library and then copy assemblies to Unity assets. I see that there is a [way ](https://docs.unity3d.com/Manual/roslyn-analyzers.html) to enable source generators for unity. However, I did not try it.

Maybe I could add ZeroQL.Unity with this to the repo?

**Comment by JuanuMusic** [comment]
I see... how did you set up the generator. The documentation shows for static strings... 

Sorry, I have not throughly gone through how tghe generator is used on ZeroQL

**Comment by byme8** [comment]
I have written the initial draft of instructions for using the library inside Unity. 
Have a look: https://github.com/byme8/ZeroQL/wiki/Unity-setup

**Comment by JuanuMusic** [comment]
Thanks a lot! This allows me to move forward 

> I have written the initial draft of instructions for using the library inside Unity. Have a look: https://github.com/byme8/ZeroQL/wiki/Unity-setup

Thanks so much! This will allow me to move forward with my project! I will reference to this link on the docs to set up the projects.

Thanks again!

**Pull request merged**
