### PR TITLE
Support for default values on scalars defined by the GraphQL …

### PR DESCRIPTION
**Pull request by DaveRMaltby**
... specification.

### CODE REVIEW

**Comment by DaveRMaltby** [comment]
It is unclear to me why the diff on 2 of the files in this commit indicate that everything in the file has changed, while the other 2 files properly show just what changed.

**Comment by byme8** [comment]
> diff on 2 of the files in this commit indicate that everything in the file has changed

I suppose it is related to the line endings. Not sure about it need to check

**Comment by DaveRMaltby** [comment]
> > diff on 2 of the files in this commit indicate that everything in the file has changed
> 
> I suppose it is related to the line endings. Not sure about it need to check

I'll play with it and see if I can figure it out, since it makes things tougher for you to review.

**Comment by DaveRMaltby** [comment]
> From a review perspective, it doesn't matter. Github allows to ignore whitespace in diff
Ahh... cool.. 

Anyhow, just found out it is easy to figure out in Visual Studio... 

image

In the bottom right corner of the editor, it says what the line endings are in the open file.  As you can see there, it is MIXED.  If you click on that, then you can have it change all line endings to CR\LF or LF with a single click.

**Comment by DaveRMaltby** [comment]
Ok.  Figured it out.  Push a commit to properly standardize on the line endings.  Happy now.  :)

**Comment by byme8** [comment]
Git can auto-fix line endings:
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Comment by byme8** [comment]
I created .gitattributes in the main branch. It should avoid issues with line endings in the future.

**Comment by DaveRMaltby** [comment]
> I created .gitattributes in the main branch. It should avoid issues with line endings in the future.

Thank you, sir!

**Pull request merged**
